import DraftsOutlinedIcon from '@mui/icons-material/DraftsOutlined';
import AccessTimeOutlinedIcon from '@mui/icons-material/AccessTimeOutlined';
import FavoriteBorderOutlinedIcon from '@mui/icons-material/FavoriteBorderOutlined';
import HomeOutlinedIcon from '@mui/icons-material/HomeOutlined';
import WidgetsOutlinedIcon from '@mui/icons-material/WidgetsOutlined';
import LibraryBooksOutlinedIcon from '@mui/icons-material/LibraryBooksOutlined';
import CardGiftcardOutlinedIcon from '@mui/icons-material/CardGiftcardOutlined';
import TakeoutDiningOutlinedIcon from '@mui/icons-material/TakeoutDiningOutlined';
import CloseIcon from '@mui/icons-material/Close';
import SearchIcon from '@mui/icons-material/Search';
import MoreHoriz from '@mui/icons-material/MoreHoriz';
import DragIndicator from '@mui/icons-material/DragIndicator';
import CreateOutlinedIcon from '@mui/icons-material/CreateOutlined';
import FileUploadOutlinedIcon from '@mui/icons-material/FileUploadOutlined';
import CropSharpIcon from '@mui/icons-material/CropSharp';
import RemoveIcon from '@mui/icons-material/Remove';
import AddIcon from '@mui/icons-material/Add';
import LinkOffOutlinedIcon from '@mui/icons-material/LinkOffOutlined';
export const DraftsOutline = () => <DraftsOutlinedIcon />;
export const AccessTimeOutlined = () => <AccessTimeOutlinedIcon />;
export const FavoriteBorderOutlined = () => <FavoriteBorderOutlinedIcon />;
export const HomeOutlined = () => <HomeOutlinedIcon />;
export const WidgetsOutlined = () => <WidgetsOutlinedIcon />;
export const LibraryBooksOutlined = () => <LibraryBooksOutlinedIcon />;
export const CardGiftcardOutlined = () => <CardGiftcardOutlinedIcon />;
export const TakeoutDiningOutlined = () => <TakeoutDiningOutlinedIcon />;
export const Close = () => <CloseIcon />;
export const Search = () => <SearchIcon />;
export const MoreHorizIcon = () => <MoreHoriz />;
export const DragIndicatorIcon = ({ ...otherProps }) => <DragIndicator {...otherProps} />;
export const Edit = () => <CreateOutlinedIcon />;
export const FileUploadOutline = ({ ...otherProps }) => <FileUploadOutlinedIcon {...otherProps} />;
export const CropSharp = ({ ...otherProps }) => <CropSharpIcon {...otherProps} />;
export const Remove = ({ ...otherProps }) => <RemoveIcon {...otherProps} />;
export const Add = ({ ...otherProps }) => <AddIcon {...otherProps} />;
export const LinkOffOutlined = ({ ...otherProps }) => <LinkOffOutlinedIcon {...otherProps} />;
